- hosts: localhost
  connection: local
  gather_facts: false
  tasks:

    - name: Create RDS instance
      import_role:
        name: roles/create-rds-role

    - name: Create VPC peering
      import_role:
        name: roles/vpc-peering-role