- hosts: localhost
  connection: local
  gather_facts: false
  tasks:

  - import_role:
      name: roles/setup-cluster-role

  - import_role:
      name: roles/metrics-server

  - import_role:
      name: roles/cluster-autoscaler