#Replica set to deploy docker image
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  namespace: ui
  labels:
    app: userinterface
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: userinterface-recipeapp
          image: yogitapatil/front_end:645b013d8d84caa6b6fe06373cc107ba350262cd
          env:
            - name: REACT_APP_BACKENDURL
              valueFrom:
                configMapKeyRef:
                  name: backend-config-map
                  key: BACKENDURL
          ports:
            - containerPort: 4000
          resources:
            requests:
              memory: "250Mi"
            limits:
              memory: "500Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 20
            periodSeconds: 10
      initContainers:
        - name: init-backendservice
          image: busybox
          command: ['sh', '-c', 'until nslookup apiservice.api.svc.cluster.local; do echo waiting for apiservice.api; sleep 2; done;']
      imagePullSecrets:
        - name: regcred
