#Creating Load Balancer Service
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: api
  labels:
    app: webapp
spec:
  selector:
    tier: backend
  ports:
    - port: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-api-svc
  namespace: api
  labels:
    app: webapp
spec:
  ports:
    - port: 300
      protocol: TCP
      targetPort: 3000
  selector:
    tier: backend