#Replica set to deploy docker image
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend
  namespace: api
  labels:
    app: webapp
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
        - name: private-reg-container
          image: baruamayank92/back-end:5f990b3346aa4732041c2d5f3e465aff9967a60f
          envFrom:
            - configMapRef:
                name: env-config
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /howyoudoin
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /howyoudoin
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              memory: "250Mi"
            limits:
              memory: "500Mi"
      imagePullSecrets:
        - name: regcred
