---
- name: Creating Name Space
  command: "kubectl apply -f roles/config-cluster/tasks/name_space.yaml"

- name: Creating Secret
  shell: "kubectl apply -f roles/config-cluster/tasks/create_secret.yaml"

- name: Creating Config Map
  shell: "kubectl apply -f roles/config-cluster/tasks/create_config_map.yaml"

- name: Creating Replica Set
  shell: "kubectl apply -f roles/config-cluster/tasks/create_replica_set.yaml"

- name: Creating Load Balancer
  shell: "kubectl apply -f roles/config-cluster/tasks/create_load_balancer.yaml"

...

