---
# vars file for setup-cluster-role
  bastion: true

  aws_region: us-east-1

  master_volume_size: 50

  topology: private

  kubernetes_networking: amazon-vpc-routed-eni

  prod_az_count: 3
  env: dev
  az_array: []
...
