---
# tasks file for teardown-rds-role

- name: delete rds
  rds:
    command: delete
    profile: "{{ env }}"
    region: "{{ aws_region }}"
    instance_name: "{{ rds_instancename }}"
    wait: yes

- name: Delete RDS subnet
  rds_subnet_group:
    state: absent
    profile: "{{ env }}"
    region: "{{ aws_region }}"
    name: "{{rds_subnetgroup}}"

- name: Security group info
  ec2_group_info:
    profile: "{{ env }}"
    region: "{{ aws_region }}"
    filters:
      group-name: "{{ rds_securitygroup }}"
  register: security_details

- debug : var=security_details

- name: Delete security group
  ec2_group:
    description: Ec2 Security group
    region: "{{ aws_region }}"
    profile: "{{ env }}"
    group_id: "{{security_details.security_groups[0].group_id}}"
    state: absent
  when: security_details.security_groups|length != 0